export const YASVIK_THEME_PRESETS = [
  {
    key: 'primepack-lime',
    label: 'Primepack Lime',
    descriptor: 'The Luminous Storefront',
    bestFor: 'High-visibility quick commerce, energetic offers, and a bold premium-natural storefront feel.',
    bgCanvas: '#F5F9EA',
    bgCard: '#FFFDF3',
    textMain: '#082514',
    actionPrimary: '#49CF43',
    actionText: '#07130E',
    accent: '#34C230',
    muted: '#4E604A',
    border: 'rgba(8, 69, 36, 0.18)',
    header: '#06351F',
    headerText: '#FFFFFF',
  },
  {
    key: 'premium-light',
    label: 'Premium Light',
    descriptor: 'The Purity Baseline',
    bestFor: 'Standard daytime operations, dairy drops, and foundational trust.',
    bgCanvas: '#FFFFFF',
    bgCard: '#FFFFFF',
    textMain: '#1A1A1A',
    actionPrimary: '#00E676',
    actionText: '#1A1A1A',
    accent: '#00B85C',
    muted: '#667065',
    border: 'rgba(26, 26, 26, 0.12)',
    header: '#23714B',
    headerText: '#FFFFFF',
  },
  {
    key: 'monsoon-indigo',
    label: 'Monsoon Indigo',
    descriptor: 'The Cinematic Night',
    bestFor: 'Night mode, glass jars, glowing ingredient photography, premium tech energy.',
    bgCanvas: '#121330',
    bgCard: '#1C1D42',
    textMain: '#E5E6ED',
    actionPrimary: '#CEFF00',
    actionText: '#121330',
    accent: '#C46210',
    muted: '#AEB2CF',
    border: 'rgba(229, 230, 237, 0.16)',
    header: '#121330',
    headerText: '#E5E6ED',
  },
  {
    key: 'earth-harvest',
    label: 'Earth & Harvest',
    descriptor: 'The Raw Heritage',
    bestFor: 'Heritage millets, hand-pounded spices, autumn and festival campaigns.',
    bgCanvas: '#FBF9F6',
    bgCard: '#FFFFFF',
    textMain: '#2B2621',
    actionPrimary: '#C46210',
    actionText: '#FFFFFF',
    accent: '#7F4B20',
    muted: '#796B5E',
    border: 'rgba(196, 98, 16, 0.18)',
    header: '#315C35',
    headerText: '#FFFFFF',
  },
  {
    key: 'midnight-forest',
    label: 'Midnight Forest',
    descriptor: 'The Luxury Canopy',
    bestFor: 'Wild honey, saffron staples, limited drops, and premium gift boxes.',
    bgCanvas: '#0B130E',
    bgCard: '#14221A',
    textMain: '#F4F1EA',
    actionPrimary: '#D4AF37',
    actionText: '#0B130E',
    accent: '#A46D24',
    muted: '#B6C2B2',
    border: 'rgba(244, 241, 234, 0.16)',
    header: '#14221A',
    headerText: '#F4F1EA',
  },
  {
    key: 'clean-slate',
    label: 'Clean Slate',
    descriptor: 'The Tech-Hygienic Minimalist',
    bestFor: 'Lab testing, pesticide-free clearances, and purity metrics.',
    bgCanvas: '#F0F2F5',
    bgCard: '#FFFFFF',
    textMain: '#0F172A',
    actionPrimary: '#00F5A0',
    actionText: '#0F172A',
    accent: '#0EA5A4',
    muted: '#64748B',
    border: 'rgba(15, 23, 42, 0.14)',
    header: '#0F5132',
    headerText: '#FFFFFF',
  },
  {
    key: 'saffron-sunrise',
    label: 'Saffron Sunrise',
    descriptor: 'The High-Energy Morning',
    bestFor: 'Breakfast windows, flash sales, and impulse morning shopping.',
    bgCanvas: '#FAFAFA',
    bgCard: '#FFFFFF',
    textMain: '#1C1C1C',
    actionPrimary: '#FF6D00',
    actionText: '#FFFFFF',
    accent: '#B84A00',
    muted: '#6B625B',
    border: 'rgba(255, 109, 0, 0.17)',
    header: '#315C35',
    headerText: '#FFFFFF',
  },
];

export const DEFAULT_THEME_PRESET_KEY = 'primepack-lime';

export function getThemePreset(key = DEFAULT_THEME_PRESET_KEY) {
  return YASVIK_THEME_PRESETS.find((theme) => theme.key === key) || YASVIK_THEME_PRESETS.find((theme) => theme.key === DEFAULT_THEME_PRESET_KEY);
}

export function getThemeCssVars(theme) {
  const preset = getThemePreset(theme?.key || theme);
  return {
    '--bg-canvas': preset.bgCanvas,
    '--bg-card': preset.bgCard,
    '--text-main': preset.textMain,
    '--action-primary': preset.actionPrimary,
    '--action-text': preset.actionText,
    '--theme-accent': preset.accent,
    '--theme-muted': preset.muted,
    '--theme-border': preset.border,
    '--theme-header': preset.header,
    '--theme-header-text': preset.headerText,
    '--ysv-monsoon': preset.bgCanvas,
    '--ysv-paddy': preset.actionPrimary,
    '--ysv-copper': preset.accent,
    '--ysv-silver': preset.textMain,
    '--ysv-surface-page': preset.bgCanvas,
    '--ysv-surface-paper': preset.bgCard,
    '--ysv-text-primary': preset.textMain,
    '--ysv-text-muted': preset.muted,
    '--ysv-border-soft': preset.border,
    '--ysv-border-paper': preset.border,
    '--ysv-focus-ring': `${preset.actionPrimary}66`,
    '--yasvik-dynamic-bg': preset.bgCanvas,
  };
}
