import { YASVIK_FSSAI_LICENSE, YASVIK_LABEL_WEBSITE, YASVIK_SHELF_LIFE } from '@/lib/yasvikSeznikLabelLayout';

export const DEFAULT_FSSAI_LOGO_URL = '/media/fssai-logo.svg';

export function createDefaultGroceryTemplate() {
  return {
    id: 'grocery-50x25',
    name: 'Grocery 50×25 (Yasvik)',
    widthMm: 50,
    heightMm: 25,
    safeMarginMm: 2.5,
    assets: {
      fssaiLogoUrl: DEFAULT_FSSAI_LOGO_URL,
    },
    elements: [
      {
        id: 'title',
        type: 'field',
        fieldKey: 'productTitle',
        xMm: 25,
        yMm: 1.35,
        anchor: 'center',
        baseline: 'top',
        align: 'center',
        fontFamily: 'mixed',
        fontSizeMm: 3.0,
        minFontSizeMm: 2.0,
        fontWeight: 700,
        color: '#000000',
        maxWidthMm: 46,
        multiLine: true,
        lineGapMm: 0.75,
        visible: true,
      },
      {
        id: 'divider',
        type: 'line',
        xMm: 2.5,
        yMm: 5.4,
        widthMm: 45,
        strokeMm: 0.14,
        color: '#000000',
        visible: true,
      },
      {
        id: 'price',
        type: 'field',
        fieldKey: 'price',
        prefix: 'Price: ₹',
        xMm: 2.5,
        yMm: 6.1,
        anchor: 'left',
        baseline: 'top',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 3.1,
        minFontSizeMm: 2.4,
        fontWeight: 700,
        color: '#000000',
        maxWidthMm: 21,
        visible: true,
      },
      {
        id: 'netWt',
        type: 'field',
        fieldKey: 'netWt',
        prefix: 'Net wt: ',
        xMm: 2.5,
        yMm: 9.8,
        anchor: 'left',
        baseline: 'top',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 3.1,
        minFontSizeMm: 2.4,
        fontWeight: 700,
        color: '#000000',
        maxWidthMm: 21,
        visible: true,
      },
      {
        id: 'packedDate',
        type: 'field',
        fieldKey: 'packedDate',
        prefix: 'Pkd: ',
        xMm: 26.5,
        yMm: 6.3,
        anchor: 'left',
        baseline: 'top',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 2.2,
        fontWeight: 400,
        color: '#000000',
        maxWidthMm: 21,
        visible: true,
      },
      {
        id: 'batchNo',
        type: 'field',
        fieldKey: 'batchNo',
        prefix: 'B: ',
        xMm: 26.5,
        yMm: 8.8,
        anchor: 'left',
        baseline: 'top',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 2.2,
        fontWeight: 400,
        color: '#000000',
        maxWidthMm: 21,
        visible: true,
      },
      {
        id: 'shelfLife',
        type: 'field',
        fieldKey: 'shelfLife',
        xMm: 26.5,
        yMm: 11.3,
        anchor: 'left',
        baseline: 'top',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 1.9,
        minFontSizeMm: 1.5,
        fontWeight: 400,
        color: '#000000',
        maxWidthMm: 21,
        visible: true,
      },
      {
        id: 'productBarcode',
        type: 'barcode',
        fieldKey: 'productBarcode',
        xMm: 27,
        yMm: 5.5,
        anchor: 'left',
        baseline: 'top',
        widthMm: 22,
        heightMm: 8,
        showValue: true,
        color: '#000000',
        visible: true,
      },
      {
        id: 'fssaiLogo',
        type: 'image',
        assetKey: 'fssaiLogo',
        xMm: 2.5,
        yMm: 20.4,
        anchor: 'left',
        baseline: 'top',
        heightMm: 1.9,
        visible: true,
      },
      {
        id: 'fssaiLicense',
        type: 'field',
        fieldKey: 'fssaiLicense',
        prefix: 'Lic.No.',
        xMm: 8.4,
        yMm: 21.3,
        anchor: 'left',
        baseline: 'middle',
        align: 'left',
        fontFamily: 'arial',
        fontSizeMm: 1.75,
        fontWeight: 400,
        color: '#000000',
        maxWidthMm: 24,
        visible: true,
      },
      {
        id: 'website',
        type: 'field',
        fieldKey: 'website',
        xMm: 47.5,
        yMm: 21.3,
        anchor: 'right',
        baseline: 'middle',
        align: 'right',
        fontFamily: 'arial',
        fontSizeMm: 1.75,
        fontWeight: 400,
        color: '#000000',
        maxWidthMm: 20,
        visible: true,
      },
    ],
    meta: {
      shelfLifeDefault: YASVIK_SHELF_LIFE,
      fssaiLicenseDefault: YASVIK_FSSAI_LICENSE,
      websiteDefault: YASVIK_LABEL_WEBSITE,
    },
  };
}

export function createBlankTemplate(name = 'New template') {
  const id = `tpl-${Date.now().toString(36)}`;
  return {
    id,
    name,
    widthMm: 50,
    heightMm: 25,
    safeMarginMm: 2.5,
    assets: { fssaiLogoUrl: DEFAULT_FSSAI_LOGO_URL },
    elements: [],
    meta: {},
  };
}
